{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.jasonpearson.auto-mobile",
    "module": "auto-mobile-junit-runner",
    "version": "0.0.13-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.jasonpearson.auto-mobile",
          "module": "auto-mobile-test-plan-validation",
          "version": {
            "requires": "0.0.13-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "auto-mobile-junit-runner-0.0.13-SNAPSHOT.jar",
          "url": "auto-mobile-junit-runner-0.0.13-SNAPSHOT.jar",
          "size": 377725,
          "sha512": "941dc44d8306ed267133fb87755994d492b108d6d5a6bc7d7019bae9fa6a2d666d0607c427755f7d5dd28b1433e37cf9a0b9aa365c3adfefd5558957f4da4201",
          "sha256": "ea57a91260f7d58ced8d7d343b0ae510aafb4319f3084aeecc73cfc920ee6908",
          "sha1": "0a0ee3f702816e10a80f1e80f0b6a042652b78f5",
          "md5": "17ea4e22d39be589c244ab83d2b2ad53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "6.0.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "com.networknt",
          "module": "json-schema-validator",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "ai.koog",
          "module": "koog-agents",
          "version": {
            "requires": "0.6.3"
          }
        },
        {
          "group": "dev.jasonpearson.auto-mobile",
          "module": "auto-mobile-test-plan-validation",
          "version": {
            "requires": "0.0.13-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "auto-mobile-junit-runner-0.0.13-SNAPSHOT.jar",
          "url": "auto-mobile-junit-runner-0.0.13-SNAPSHOT.jar",
          "size": 377725,
          "sha512": "941dc44d8306ed267133fb87755994d492b108d6d5a6bc7d7019bae9fa6a2d666d0607c427755f7d5dd28b1433e37cf9a0b9aa365c3adfefd5558957f4da4201",
          "sha256": "ea57a91260f7d58ced8d7d343b0ae510aafb4319f3084aeecc73cfc920ee6908",
          "sha1": "0a0ee3f702816e10a80f1e80f0b6a042652b78f5",
          "md5": "17ea4e22d39be589c244ab83d2b2ad53"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "auto-mobile-junit-runner-0.0.13-SNAPSHOT-sources.jar",
          "url": "auto-mobile-junit-runner-0.0.13-SNAPSHOT-sources.jar",
          "size": 51262,
          "sha512": "37c6ba02859611914a85f22af973fab36a90c075ccc7e9c76034ab7e665ffc86c6f72e45de650b5ecee87cf852e0d036fa2e5476f6f4986a71d11a55676ff360",
          "sha256": "33f31ecf9b75776e66ff95156c195e1c57518f94afeb19aed122e19463e6b39a",
          "sha1": "0e5a02f0f8d4eb58a8a7cec8ba1e37ed53d847be",
          "md5": "97bbd28fc87c135812235153bd18ac6b"
        }
      ]
    }
  ]
}
