{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.jasonpearson.auto-mobile",
    "module": "auto-mobile-test-plan-validation",
    "version": "0.0.13-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "auto-mobile-test-plan-validation-0.0.13-SNAPSHOT.jar",
          "url": "auto-mobile-test-plan-validation-0.0.13-SNAPSHOT.jar",
          "size": 165865,
          "sha512": "90932813b89af90c5aac5a08cda52becc718c9f3407acec39bab76032dec13ee3a3dd61bf47d8004926469ba55fd5bfd154c98136474f7f017ce95feef4f2ab3",
          "sha256": "1ab711abef7dbace42503cdd373f27f2c70aa20d6ee957cda2de758f391f1e70",
          "sha1": "c8170adc72bc121dfe876dc583a095b695135cca",
          "md5": "07c04dd6e04144bddd168a2ae9498493"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "com.networknt",
          "module": "json-schema-validator",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        }
      ],
      "files": [
        {
          "name": "auto-mobile-test-plan-validation-0.0.13-SNAPSHOT.jar",
          "url": "auto-mobile-test-plan-validation-0.0.13-SNAPSHOT.jar",
          "size": 165865,
          "sha512": "90932813b89af90c5aac5a08cda52becc718c9f3407acec39bab76032dec13ee3a3dd61bf47d8004926469ba55fd5bfd154c98136474f7f017ce95feef4f2ab3",
          "sha256": "1ab711abef7dbace42503cdd373f27f2c70aa20d6ee957cda2de758f391f1e70",
          "sha1": "c8170adc72bc121dfe876dc583a095b695135cca",
          "md5": "07c04dd6e04144bddd168a2ae9498493"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "auto-mobile-test-plan-validation-0.0.13-SNAPSHOT-sources.jar",
          "url": "auto-mobile-test-plan-validation-0.0.13-SNAPSHOT-sources.jar",
          "size": 11296,
          "sha512": "385336507f10488226ab4cb7268ecb85ccb4e592919ed11a27091ac09f8f9ebb83336ee09213c83001ab2ae6b534c7a43bf5c7bf288a6ea9b4168e1d86268b54",
          "sha256": "ea44dd36ea03f67e8806abd0f7582e3abff83daaf12e7756873b9d99df3e9108",
          "sha1": "5087d990b94a44e9c9dc93c5a08ab3778f692606",
          "md5": "99a7ef08ea75610f7f8e4ab4fe9e35f2"
        }
      ]
    }
  ]
}
